version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DockerfileApi
    expose:
      - 80:80
      - 443:443
  app:
    build:
      context: .
      dockerfile: DockerfileUI # Pendign to create
    expose:
      - 80:80
      - 443:443
  db:
    image: postgres:14.3
    expose:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres      
    
volumes:
  postgres-data:
  
networks:
  frontend:
  backend:
